- .gitignore
- README.md
- module/actor/actor-covenant-sheet.js
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-magic-codex-sheet.js
- module/actor/actor-npc-sheet.js
- module/actor/actor-pc-sheet.js
- module/actor/actor-sheet.js
- module/arm5e.js
- module/item/item-magic-sheet.js
- module/item/item-sheet.js
- module/item/item.js
- system.json
- template.json
- templates/actor/actor-npc-sheet.html
- templates/item/item-magicalEffect-sheet.html
- templates/item/item-weapon-sheet.html
- ritual check box fixed
- confidence for NPCs is back
> New sheet design bug fixes

- lang/en.json
- module/actor/actor-pc.js
- module/actor/actor-sheet.js
- module/dice.js
- module/metadata.js
- templates/actor/parts/actor-abilities.html
- templates/actor/parts/actor-arts.html
- templates/actor/parts/actor-characteristics.html
- templates/roll/roll-spell.html
- added title to roll chat-entries.
> Rolls improvements

- module/dice.js
- Roll fields Aura, Fatigue and Wounds are not displayed in chat-log roll entries if value is 0
> Chat log improvements

- ReleaseNotes.md
- lang/en.json
- lang/es.json
- lang/fr.json
- lang/it.json
- module/actor/actor-covenant-sheet.js
- module/actor/actor-pc.js
- module/actor/actor-sheet.js
- module/dice.js
- module/metadata.js
- system.json
- template.json
- templates/actor/actor-covenant-sheet.html
- templates/actor/actor-pc-sheet.html
- templates/actor/parts/actor-covenantAtributes.html
- templates/actor/parts/actor-covenantHabitants.html
- templates/actor/parts/actor-covenantPosessions.html
- templates/generic/simpleListPicker.html
- new way to open covenant members sheets
- fixed spell rolls with magical focus to multiply the correct art
- renamed "Possessions" list in covenant to "Properties and land"
- moved covenant Calendar to diary tab
- fixed magicaL focus casting total computation
- labels of covenant build points are properly displayed again.
> - added description field to covenant actors

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-covenant-sheet.js
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-npc-sheet.js
- module/actor/actor-pc-sheet.js
- module/actor/actor-pc.js
- module/item/item.js
- module/metadata.js
- module/templates.js
- module/tools.js
- template.json
- templates/actor/actor-covenant-sheet.html
- templates/actor/parts/actor-covenantHabitants.html
- templates/actor/parts/actor-covenantPosessions.html
- templates/generic/source.html
- templates/item/item-ability-sheet.html
- templates/item/item-baseEffect-sheet.html
- templates/item/item-book-sheet.html
- templates/item/item-enchantment-sheet.html
- templates/item/item-flaw-sheet.html
- templates/item/item-labCovenant-sheet.html
- templates/item/item-laboratoryText-sheet.html
- templates/item/item-magicItem-sheet.html
- templates/item/item-mundaneBook-sheet.html
- templates/item/item-spell-sheet.html
- templates/item/item-virtue-sheet.html
- characters can have a lab
- labs, covenants and characters can be dropped on each other to assign their respective values
- new "Other" option for range, duration and target spell attributes
> - covenants have labs/sanctums

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor-pc.js
- module/actor/actor-sheet.js
- module/dice.js
- templates/actor/parts/actor-fatigue.html
- dead characters are no longer able to roll
- unconscious characters are only able to roll characteristics rolls
- new "Rest" button to recover all fatigue levels
> - spontaneous magic rolls makes the caster loose a fatigue level.

- ReleaseNotes.md
- module/actor/actor-pc.js
- module/item/item.js
- system.json
- template.json
- templates/actor/actor-magic-codex-sheet.html
- templates/item/item-abilityFamiliar-sheet.html
- templates/item/item-distinctive-sheet.html
- templates/item/item-incomingSource-sheet.html
- templates/item/item-personality-sheet.html
- templates/item/item-powerFamiliar-sheet.html
- templates/item/item-reputation-sheet.html
- templates/item/item-sanctumRoom-sheet.html
- templates/item/item-speciality-sheet.html
- templates/item/item-spell-sheet.html
- templates/item/parts/spell-design.html
- new filter options in Codex (>=, <=,...)
- Fixed footer display problem in Codex
- Fixed remaing item sheets without image.
> - spells have now a "General" attribute used to compute the level.

- module/actor/actor-sheet.js
- Calculate valid message when wound is effective
> Another bug

- templates/actor/parts/actor-voice-and-gestures.html
Sorry for the flood of PR. This is a very stupid thingy my player found
> Stupid bug

- ReleaseNotes.md
- lang/en.json
- module/arm5e.js
- module/constants/activeEffectsTypes.js
- module/dice.js
- templates/actor/parts/actor-combat.html
- templates/generic/active-effect-config.html
- templates/generic/infoBox.html
- fun stress dice rolls option
- new AE
- characteristics
- fatigue penalties
- wound penalties
> More active effects modes

- module/actor/actor-pc.js
> Quick fix for crisis negative score in char

- lang/en.json
- module/config.js
- module/migration.js
- template.json
- templates/actor/actor-npc-sheet.html
> fix bug in decrepitude migration

- .prettierrc.json
- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- lang/es.json
- module/actor/actor-pc.js
- module/actor/actor-sheet.js
- module/arm5e.js
- module/helpers/long-term-activities.js
- module/migration.js
- module/templates.js
- template.json
- templates/actor/actor-npc-sheet.html
- templates/actor/actor-pc-sheet.html
- templates/actor/parts/actor-covenantEconomics.html
- templates/actor/parts/actor-covenantLibrary.html
- templates/actor/parts/actor-description.html
- templates/actor/parts/hermeticFilter.html
- templates/generic/active-effect-config.html
- templates/generic/source.html
- templates/item/item-armor-sheet.html
- templates/item/item-book-sheet.html
- templates/item/item-habitantHabitants-sheet.html
- templates/item/item-mundaneBook-sheet.html
- templates/item/item-visSourcesCovenant-sheet.html
- templates/item/parts/item-enchantment.html
- templates/roll/roll-magic.html
> - Fixed crisis bug

- ReleaseNotes.md
- module/arm5e.js
- module/config.js
- module/dice.js
- module/helpers/rollWindow.js
- module/item/item-converter.js
- module/item/item-sheet.js
- module/item/item.js
- templates/item/item-laboratoryText-sheet.html
- templates/item/item-spell-sheet.html
Xps of mastery reset properly on drop
> Magic rules enforcement removed

- ReleaseNotes.md
- module/actor/actor-sheet.js
- module/helpers/spells.js
- module/item/item.js
- templates/actor/parts/actor-arts.html
- Only spells strictly greater than level 50 become rituals
> Requisites are displayed in spell/magical effects lists

- ReleaseNotes.md
- module/actor/actor-beast-sheet.js
- module/dice.js
- module/helpers/chat.js
- module/helpers/magic.js
- module/helpers/rollWindow.js
- templates/actor/parts/actor-powerUse.html
- This is a quick and dirty one. Everything will be rewritten when the rework on roll data will be done.
> Powers integration in contests of magic

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-pc.js
- module/actor/actor-sheet.js
- module/config.js
- module/constants/activeEffectsTypes.js
- module/helpers/long-term-activities.js
- module/item/item-diary-sheet.js
- module/item/item.js
- module/migration.js
- template.json
- templates/item/parts/seasonal-activity.html
> - Practice seasonal activity type

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor-pc.js
- module/constants/activeEffectsTypes.js
- module/item/item-diary-sheet.js
- module/item/item.js
- module/tools.js
- templates/item/parts/activities.html
- Cosmetic improvements of activities
- When using an unlinked teacher:
- only show abilities and arts which are lower than the teacher score
- allow editing the Teaching field
- Teaching speciality is properly taken into account.
- Simplified code a bit
> - Activities small improvements and bug fixes

- ReleaseNotes.md
- module/actor/actor-pc.js
- module/item/item-diary-sheet.js
- system.json
- Parma magica , penetration and teaching were not taking into account active effects (eg Puissant) in some cases
- Fixed empty dropbox for Arts progression in adventuring and exposure.
> - Magi NPCs have their magic resistance properly computed

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/constants/activeEffectsTypes.js
- module/helpers/active-effects.js
- module/helpers/aura.js
- module/helpers/long-term-activities.js
- module/helpers/magic.js
- module/item/item-book-sheet.js
- system.json
- templates/actor/parts/actor-lab-workbench.html
- templates/roll/roll-spell.html
- details of lab total computation
- added mnemonics for translations
- modifiers for lab total are added before division due to deficient art.
- lab activities active effects.
-
> - Lab acitivity small improvements

- ReleaseNotes.md
- lang/en.json
- lang/es.json
- lang/fr.json
- lang/it.json
- lang/pt.json
- module/actor/actor.js
- module/helpers/combat.js
- module/helpers/items-helpers.js
- module/schemas/weaponArmorSchema.js
- module/tests/testData.js
- system.json
- templates/actor/parts/actor-armor.html
- templates/actor/parts/actor-weapons.html
- templates/generic/quick-combat.html
- templates/item/item-armor-sheet.html
- templates/item/item-weapon-sheet.html
- Quick combat and quick vitals macro dialogs are now notified and updated when changes occurs on the token
- Equipped flag was omitted in the weapon schema
- Quick vitals is properly sized
- Fatigue overflow is now working properly
- Migration
- Weapon.load not a number
> - QuickXXX macro notified on update + bug fixes

- ReleaseNotes.md
- system.json
- website/UserGuide/Gameplay.md
- website/UserGuide/Items.md
- website/UserGuide/Laboratory activities.md
- website/UserGuide/Long term activities.md
> User guide update

- ReleaseNotes.md
- css/arm5e.css
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/dice.js
- module/helpers/combat.js
- module/helpers/rollWindow.js
- module/item/item.js
- module/schemas/woundSchema.js
- module/tools/sanatorium.js
- system.json
- templates/actor/parts/actor-fatigue.html
- templates/generic/quick-vitals.html
- templates/generic/sanatorium.html
- Wound penalty computation done after roll period.
- Finishing touches
> 2.1.1 mercere recovery final before release

- ReleaseNotes.md
- module/actor/actor-laboratory-sheet.js
- module/actor/actor.js
- module/arm5e.js
- module/config.js
- module/helpers/active-effects.js
- module/helpers/rollData.js
- module/item/item-diary-sheet.js
- module/item/item-sheet.js
- module/item/item.js
- module/migration.js
- module/schemas/woundSchema.js
- system.json
- template.json
- templates/actor/parts/actor-armor.html
- templates/actor/parts/actor-items.html
- templates/actor/parts/actor-weapons.html
- templates/item/item-armor-sheet.html
- templates/item/item-weapon-sheet.html
- Added quantity of items in inventory tab.
- Edition of transferred active effect (eg: from a virtue or flaw) is now possible (V11 only)
- Vis extracted from aura is now dropped in the lab inventory
- Checkbox to equip / take off weapons and armors from the character sheet is back
- It is again possible for players to drop teachers on a Teaching activity sheet
> 2.2.2 nicodemus

- ReleaseNotes.md
- module/actor/actor-sheet.js
- module/helpers/active-effects.js
- module/migration.js
- system.json
Fixed display of transferred effects
Fix migration of suppressed effects
> Active effect V11 fix

- ReleaseNotes.md
- module/constants/activeEffectsTypes.js
- module/item/item-diary-sheet.js
- system.json
- templates/generic/active-effect-config.html
- add back realm alignment active effect
> - Fix teaching activity

- ReleaseNotes.md
- css/arm5e.css
- module/actor/actor-sheet.js
- module/arm5e.js
- module/constants/activeEffectsTypes.js
- module/helpers/active-effect-config.sheet.js
- module/helpers/active-effects.js
- system.json
- templates/generic/aging-dialog.html
- templates/generic/aura-config.html
- templates/generic/vis-study.html
- Compendia indexes are computed later as they were not ready in V10
- Active effects are again editable in V10
- Fixed background size in dialogs
> 2.2.2 nicodemus BF

- .gitignore
- ReleaseNotes.md
- lang/en.json
- module/actor/actor-covenant-sheet.js
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-magic-codex-sheet.js
- module/item/item-diary-sheet.js
- module/item/item-sheet.js
- module/item/subsheet/enchant-extension-sheet.js
- module/tools/activity-schedule.js
- module/tools/astrolab.js
- module/tools/med-history.js
- module/tools/sanatorium.js
- module/tools/schedule.js
- module/tools/scriptorium.js
- system.json
- templates/item/item-diaryEntry-sheet.html
- templates/item/parts/activities.html
- templates/item/parts/enchant-extension.html
- Possible Drag and drop of Spells and Magical effects on enchantable item sheet
- Bigger area to drop them
- Dropping an enchantment on an enchantable Item will appraise it automatically.
- It is now possible to edit the begin date of a long duration event (warning: all remaining seasons will be sequenced from that one)
- Removed a reference to the folding flags
- Schedule and activity sheets no long pop out on date change.
- Better and smoother cache initialization
> Enchanted items improvement.

- ReleaseNotes.md
- module/actor/actor-covenant-sheet.js
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-sheet.js
- module/item/item-diary-sheet.js
- module/item/subsheet/enchant-extension-sheet.js
- module/seasonal-activities/activity.js
- system.json
- templates/actor/covenant-limited-sheet.html
- templates/actor/lab-limited-sheet.html
- templates/lab-activities/minor-enchantment.html
- templates/lab-activities/spell.html
- New limited sheet for covenants and laboratories
- Fixed lab initialization when there is a new owner
- Fixed some foldable sections in the lab workbench that were not keeping their state between sessions
> Enchantment activity BF

- ReleaseNotes.md
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/arm5e.js
- module/config.js
- module/helpers/long-term-activities.js
- module/item/item-book-sheet.js
- module/item/item-diary-sheet.js
- module/item/subsheet/enchant-extension-sheet.js
- module/schemas/diarySchema.js
- module/tests/diaryAdventuringTest.js
- module/tests/diaryCharCreationTest.js
- module/tests/diaryExposureTest.js
- module/tests/diaryTeachingTest.js
- module/tests/diaryTrainingTest.js
- system.json
- templates/item/parts/activities.html
- Free choice of abilities in long term activities (ie: character doesn't need to have it to progress)
- Fixes on diary entries
- Capped spell masteries based on teacher score
- Fixed rollback of capped masteries.
- Remove xp multiplier from progressed xp.
- Actor age is now changing properly when the date changes.
> Free choice of abilities in long term activities

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-sheet.js
- module/helpers/long-term-activities.js
- module/helpers/magic.js
- module/helpers/rollData.js
- module/item/item-diary-sheet.js
- module/item/subsheet/enchant-extension-sheet.js
- module/seasonal-activities/activity.js
- module/templates.js
- system.json
- templates/actor/parts/actor-lab-workbench.html
- templates/item/parts/activities.html
- templates/item/parts/enchant-extension.html
- templates/item/parts/enchantment-attributes.html
- templates/item/parts/spell-design-V2.html
- templates/item/parts/vis-costs.html
- templates/lab-activities/minor-enchantment.html
- templates/lab-activities/spell.html
- Vis costs for enchantment activities
- Second attempt at updating the age of a character when the date changes
- It is no longer possible to roll for aging unless a year of birth is set (it defaults to 1200 at creation)
- Aging rolls are computing the age modifier based on the year of the diary entry instead of current year
> Lab vis costs + BF

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/config.js
- module/seasonal-activities/activity.js
- system.json
- templates/item/parts/seasonal-activity.html
- templates/lab-activities/minor-enchantment.html
- Aspects bonuses capped by magic theory
- Pick the type of enchanted Item to be created.
- bug fixes
> 2.2.3 ophilio

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-magic-codex-sheet.js
- module/actor/actor-npc-sheet.js
- module/actor/actor-pc-sheet.js
- module/config.js
- module/item/item-diary-sheet.js
- module/item/item-magic-sheet.js
- module/item/item.js
- module/migration.js
- module/schemas/enchantmentSchema.js
- module/seasonal-activities/activity.js
- system.json
- templates/actor/parts/actor-lab-workbench.html
- templates/item/item-enchantment-sheet.html
- templates/item/item-laboratoryText-sheet.html
- templates/item/parts/enchant-extension.html
- templates/item/parts/enchantment-attributes.html
- templates/lab-activities/charged-item.html
- Dropping a lab text on an Actor's sheet no longer add it as an effect but add it in inventory.
- Verditius magic taken into account for shapes and materials bonuses.
- Charged Items creation in lab.
- Removed dependency to arm5e-compendia at documents' initialization so higher latency servers don't raise an error.
- Migration no longer fails migrating effects of invalid actors
> Charged Items

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-beast-sheet.js
- module/actor/actor-covenant-sheet.js
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-npc-sheet.js
- module/actor/actor-pc-sheet.js
- module/actor/actor-sheet.js
- module/arm5e.js
- module/seasonal-activities/activity.js
- system.json
- Added notification warning if arm5e-compendia module version is below minimum
- Fixed name and description of diary entry causing errors on scheduling.
> Spell invention and learning fix

- ReleaseNotes.md
- system.json
- templates/item/item-diaryEntry-sheet.html
- templates/item/parts/seasonal-activity.html
> Apply button always visible

- ReleaseNotes.md
- module/helpers/rollWindow.js
- module/item/item-diary-sheet.js
- templates/actor/actor-npc-sheet.html
- templates/actor/actor-pc-sheet.html
- Partial fix of aging crisis roll
- no errors on click
- Medical assistance is properly removed from the roll instead of added.
> Aging crisis fix

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor.js
- module/arm5e.js
- module/config.js
- module/dice.js
- module/helpers/long-term-activities.js
- module/helpers/rollData.js
- module/item/item-diary-sheet.js
- module/item/item-sheet.js
- module/schemas/bookSchema.js
- module/tools/scriptorium.js
- module/ui/ars-layer.js
- system.json
- templates/actor/actor-beast-sheet.html
- templates/actor/actor-npc-sheet.html
- templates/actor/actor-pc-sheet.html
- templates/generic/activity-schedule.html
- templates/generic/aging-dialog.html
- templates/generic/character-schedule.html
- templates/generic/group-schedule.html
- templates/generic/scriptorium.html
- templates/item/item-book-sheet.html
- templates/item/item-main-sheet.html
- templates/item/parts/item-footer.html
- templates/roll/roll-aging-crisis.html
- Added macros to open canvas menu dialogs (Scriptorium, Astrolabium, Aura management)
- Rework of Reading tab in Scriptorium
- Possible to browse the topics of a book in the scriptorium.
- Improved generic ability handling
- Changing the topic of a virtual book in the Scriptorium no longer raise an error.
- Lab texts are no longer applicable in the scriptorium.
> 2.2.4 pralix

- ReleaseNotes.md
- module/actor/actor-laboratory-sheet.js
- module/config.js
- module/item/item-book-sheet.js
- module/item/subsheet/enchant-extension-sheet.js
- module/schemas/bookSchema.js
- module/templates.js
- system.json
- templates/item/item-armor-sheet.html
- templates/item/item-book-sheet.html
- templates/item/item-item-sheet.html
- templates/item/item-weapon-sheet.html
- templates/item/parts/enchant-attributes-section.html
- templates/item/parts/enchant-desc-section.html
- templates/item/parts/enchant-extension.html
- Books as magic items
- Drop a new owner on a lab will reset the lab.
> Books as magic items

- README.md
- ReleaseNotes.md
- lang/en.json
- module/actor/actor-npc-sheet.js
- module/actor/actor.js
- module/config.js
- module/item/item-book-sheet.js
- module/schemas/bookSchema.js
- module/tools/scriptorium.js
- system.json
- templates/actor/actor-npc-sheet.html
- templates/actor/parts/actor-library.html
- templates/generic/scriptorium.html
- templates/item/item-book-sheet.html
- arm5e-compendia module minimum version 0.3.0
- New general generic ability : Lore
- NPCs now also have their library tab
- Books topic on an ability will now have a dedicated field for the ability's name.
- Quality of writen tractati is computed properly
- Missing translations added
- Teamsters are again displayed in the covenant inhabitants. via the hotbar (Scriptorium, Astrolabium, ...)
> Various BFs

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/constants/activeEffectsTypes.js
- module/helpers/active-effects.js
- module/item/item.js
- module/schemas/bookSchema.js
- module/schemas/diarySchema.js
- module/schemas/enchantmentSchema.js
- module/schemas/magicSchemas.js
- module/schemas/minorItemsSchemas.js
- module/schemas/weaponArmorSchema.js
- system.json
- templates/actor/actor-laboratory-sheet.html
- templates/actor/parts/actor-lab-workbench.html
- templates/generic/simpleFieldBacksection.html
- New active effect: aura modifier for lab.
- [meta] new method for datamodel schemas : sanitize
- Lab size attribute is now computed properly.
- Partial fix to pending xp
> Sanitization + fixes

- ReleaseNotes.md
- module/helpers/rollInfo.js
- module/migration.js
- module/schemas/commonSchemas.js
- module/schemas/covenantSchema.js
- system.json
- templates/actor/actor-npc-sheet.html
- templates/roll/parts/penetration-options.html
- Fix apprentice intelligence equals to null during migration
- Rolls on beast sheet are possible again
- Penetration bonuses are computed properly again
> V12 migration BF2

- ReleaseNotes.md
- module/actor/actor-covenant-sheet.js
- module/config.js
- module/migration.js
- system.json
- template.json
- templates/actor/actor-beast-sheet.html
- templates/actor/actor-npc-sheet.html
- templates/actor/actor-pc-sheet.html
- templates/actor/parts/actor-characteristics.html
- templates/item/parts/enchant-attributes-section.html
- templates/item/parts/enchant-extension.html
- templates/roll/roll-magic.html
- Covenant data model migration (on going)
- first draft (not active)
- moved mnemonics to config
- Penetration bonuses are computed properly again
- Fix Cunning label on beast sheet
> V12 compatibility BF2

- ReleaseNotes.md
- lang/en.json
- module/actor/actor-covenant-sheet.js
- module/actor/actor.js
- module/config.js
- module/helpers/rollInfo.js
- module/schemas/covenantSchema.js
- module/schemas/inhabitantSchema.js
- system.json
- templates/actor/parts/actor-covenantHabitants.html
- templates/item/item-labCovenant-sheet.html
- loyalty computation
- Supernatural abilities sheet is no longer raising an error.
> Loyalty computation

- ReleaseNotes.md
- system.json
> Verified v12.330

- system.json
- Added social status subcategories
- Removed tainted category of virtues and flaws.
- Added a new "Tainted" flag to Virtues and Flaws
- Fix sourcebooks filters duplicates
- Sourcebooks filters were not applied properly on new worlds
> missing system.json update

- ReleaseNotes.md
- css/arm5e.css
- lang/en.json
- module/actor/actor-laboratory-sheet.js
- module/actor/actor.js
- module/config.js
- module/helpers/active-effects.js
- module/helpers/magic.js
- module/helpers/rollInfo.js
- module/item/item-diary-sheet.js
- module/seasonal-activities/activity.js
- module/templates.js
- system.json
- templates/actor/parts/actor-description.html
- templates/actor/parts/actor-lab-workbench.html
- templates/item/item-ability-sheet.html
- templates/item/parts/vis-costs.html
- templates/lab-activities/charged-item.html
- templates/lab-activities/investigation.html
- templates/lab-activities/longevity-ritual.html
- templates/lab-activities/minor-enchantment.html
- templates/lab-activities/spell.html
- New longevity ritual activity
- Setting a non-magus as the owner of a lab will no longer prevent its opening.
- Lab activity should not reset to a simple data object in some rare cases
> Longevity rituals

- FAQ.md
- ReleaseNotes.md
- lang/en.json
- module/helpers/rollInfo.js
- module/helpers/rollWindow.js
- module/item/item-magic-sheet.js
- module/schemas/abilitySchema.js
- module/schemas/powerSchemas.js
- system.json
- templates/actor/parts/actor-powerUse.html
- templates/item/item-power-sheet.html
- templates/roll/roll-twilightControl.html
- Powers can change their cost or form on use
- Powers inherit the Form of the creature using them by default.
- Fix power migration error.
- Ability-option migration no longer remove dashes
- Generic abilities without an ability option get a new randomly generated one.
> Powers migration fix & improvement
